<?php
/**
 * Generate preview/index.html from the real plugin source.
 *
 * Renders the [solar_calculator] shortcode against a thin shim of the
 * WordPress functions it uses, then inlines the plugin's own CSS and JS. The
 * preview is therefore always the actual plugin markup, not a copy that can
 * drift.
 *
 * Usage: php tools/build-preview.php
 */

define( 'ABSPATH', __DIR__ );

/* ------------------------------------------------- WordPress function shim */

function esc_attr( $text ) { return htmlspecialchars( (string) $text, ENT_QUOTES, 'UTF-8' ); }
function esc_html( $text ) { return htmlspecialchars( (string) $text, ENT_QUOTES, 'UTF-8' ); }
function esc_url( $url ) { return htmlspecialchars( (string) $url, ENT_QUOTES, 'UTF-8' ); }
function esc_url_raw( $url ) { return $url; }
function sanitize_text_field( $text ) { return strip_tags( (string) $text ); }
function sanitize_email( $email ) { return $email; }
function sanitize_key( $key ) { return preg_replace( '/[^a-z0-9_\-]/', '', strtolower( (string) $key ) ); }
function is_email( $email ) { return (bool) filter_var( $email, FILTER_VALIDATE_EMAIL ); }
function apply_filters( $hook, $value ) { return $value; }
function add_shortcode( $tag, $callback ) {}
function add_action( $hook, $callback, $priority = 10, $args = 1 ) {}
function add_filter( $hook, $callback, $priority = 10, $args = 1 ) {}
function get_option( $name, $default = false ) { return 'admin_email' === $name ? 'admin@example.com' : $default; }
function admin_url( $path = '' ) { return '/wp-admin/' . $path; }
function home_url( $path = '/' ) { return 'https://sustainaportal.com' . $path; }
function get_bloginfo( $key ) { return 'SustainaPortal'; }
function wp_create_nonce( $action ) { return 'preview-nonce'; }
function wp_json_encode( $data ) { return json_encode( $data ); }
function number_format_i18n( $number, $decimals = 0 ) { return number_format( (float) $number, $decimals ); }
function selected( $a, $b, $echo = true ) {
	$result = (string) $a === (string) $b ? ' selected="selected"' : '';
	if ( $echo ) { echo $result; }
	return $result;
}
function wp_parse_args( $args, $defaults = array() ) {
	return array_merge( $defaults, is_array( $args ) ? $args : array() );
}
function wp_list_pluck( $list, $field ) {
	return array_map( function ( $row ) use ( $field ) { return $row[ $field ]; }, $list );
}
function shortcode_atts( $pairs, $atts, $shortcode = '' ) {
	$atts = (array) $atts;
	$out  = array();
	foreach ( $pairs as $name => $default ) {
		$out[ $name ] = array_key_exists( $name, $atts ) ? $atts[ $name ] : $default;
	}
	return $out;
}

/* --------------------------------------------------------------- the shim */

$GLOBALS['spc_preview_data'] = array();

class SPC_Plugin {
	public static function enqueue_assets( array $data ) {
		$GLOBALS['spc_preview_data'] = $data;
	}
}

/* ------------------------------------------------------------------ build */

$plugin_dir = dirname( __DIR__ ) . '/solar-power-calculator';

require_once $plugin_dir . '/includes/class-spc-data.php';
require_once $plugin_dir . '/includes/class-spc-calculator.php';
require_once $plugin_dir . '/includes/class-spc-shortcode.php';

$atts = array();
foreach ( array_slice( $argv, 1 ) as $arg ) {
	if ( strpos( $arg, '=' ) !== false ) {
		list( $key, $value ) = explode( '=', $arg, 2 );
		$atts[ $key ] = $value;
	}
}

$markup = SPC_Shortcode::render( $atts );
$css    = file_get_contents( $plugin_dir . '/assets/css/solar-calculator.css' );
$js     = file_get_contents( $plugin_dir . '/assets/js/solar-calculator.js' );
$data   = json_encode( $GLOBALS['spc_preview_data'], JSON_UNESCAPED_SLASHES );

$html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Solar Power Calculator - preview</title>
<style>
body { margin: 0; padding: 32px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #eef2f5; }
@media (prefers-color-scheme: dark) { body { background: #0b1116; } }
.preview-note { max-width: 1000px; margin: 0 auto 24px; padding: 10px 14px; border-radius: 8px; background: #fff7ed; color: #7c2d12; font-size: 14px; }
@media (prefers-color-scheme: dark) { .preview-note { background: #2a1a0d; color: #fdba74; } }
.spc { padding: 28px; border-radius: 16px; box-shadow: 0 1px 3px rgba(0,0,0,.08); }
$css
</style>
</head>
<body>
<p class="preview-note">Standalone preview generated by <code>tools/build-preview.php</code>. In WordPress this is the <code>[solar_calculator]</code> shortcode.</p>
$markup
<script>window.SPC_DATA = $data;</script>
<script>
$js
</script>
</body>
</html>
HTML;

$out = dirname( __DIR__ ) . '/preview/index.html';
file_put_contents( $out, $html );

echo "Wrote {$out} (" . number_format( strlen( $html ) ) . " bytes)\n";
